<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mono_hydra</name>
  <version>0.1.0</version>
  <description>Dataset mapping, Hydra bridge, and launch package for Mono Hydra.</description>
  <maintainer email="bavanthau@eng.pdn.ac.lk">Bavantha Udugama</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>hydra</exec_depend>
  <exec_depend>hydra_ros</exec_depend>
  <exec_depend>hydra_visualizer</exec_depend>
  <exec_depend>mono_hydra_perception</exec_depend>
  <exec_depend>mono_hydra_utils</exec_depend>
  <exec_depend>mono_hydra_vio</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
